CREATE TABLE "zenflix_account" (
	"userId" varchar(255) NOT NULL,
	"type" varchar(255) NOT NULL,
	"provider" varchar(255) NOT NULL,
	"providerAccountId" varchar(255) NOT NULL,
	"refresh_token" text,
	"access_token" text,
	"expires_at" integer,
	"token_type" varchar(255),
	"scope" varchar(255),
	"id_token" text,
	"session_state" varchar(255),
	CONSTRAINT "zenflix_account_provider_providerAccountId_pk" PRIMARY KEY("provider","providerAccountId")
);
--> statement-breakpoint
CREATE TABLE "zenflix_category" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "zenflix_category_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"name" varchar(255) NOT NULL,
	"description" text,
	"createdAt" timestamp with time zone NOT NULL,
	"updatedAt" timestamp with time zone,
	CONSTRAINT "zenflix_category_name_unique" UNIQUE("name")
);
--> statement-breakpoint
CREATE TABLE "zenflix_profile" (
	"id" uuid PRIMARY KEY NOT NULL,
	"name" varchar(255) NOT NULL,
	"avatarUrl" varchar(512),
	"userId" varchar(255) NOT NULL,
	"createdAt" timestamp with time zone NOT NULL,
	"updatedAt" timestamp with time zone
);
--> statement-breakpoint
CREATE TABLE "zenflix_review" (
	"id" uuid PRIMARY KEY NOT NULL,
	"comment" text,
	"rating" integer NOT NULL,
	"videoId" uuid NOT NULL,
	"userId" varchar(255) NOT NULL,
	"createdAt" timestamp with time zone NOT NULL,
	"updatedAt" timestamp with time zone,
	CONSTRAINT "review_video_user_unique" UNIQUE("videoId","userId")
);
--> statement-breakpoint
CREATE TABLE "zenflix_session" (
	"sessionToken" varchar(255) PRIMARY KEY NOT NULL,
	"userId" varchar(255) NOT NULL,
	"expires" timestamp with time zone NOT NULL
);
--> statement-breakpoint
CREATE TABLE "zenflix_user" (
	"id" varchar(255) PRIMARY KEY NOT NULL,
	"name" varchar(255),
	"email" varchar(255) NOT NULL,
	"emailVerified" timestamp with time zone,
	"image" varchar(255),
	"firstName" varchar(255),
	"lastName" varchar(255),
	"phone" varchar(50),
	"birthDate" timestamp,
	"passwordHash" text,
	"role" varchar(20) DEFAULT 'member' NOT NULL
);
--> statement-breakpoint
CREATE TABLE "zenflix_verification_token" (
	"identifier" varchar(255) NOT NULL,
	"token" varchar(255) NOT NULL,
	"expires" timestamp with time zone NOT NULL,
	CONSTRAINT "zenflix_verification_token_identifier_token_pk" PRIMARY KEY("identifier","token")
);
--> statement-breakpoint
CREATE TABLE "zenflix_video_category" (
	"videoId" uuid NOT NULL,
	"categoryId" integer NOT NULL,
	CONSTRAINT "zenflix_video_category_videoId_categoryId_pk" PRIMARY KEY("videoId","categoryId")
);
--> statement-breakpoint
CREATE TABLE "zenflix_video" (
	"id" uuid PRIMARY KEY NOT NULL,
	"name" varchar(255) NOT NULL,
	"description" text,
	"duration" integer,
	"releaseYear" integer,
	"fileUrl" varchar(1024) NOT NULL,
	"thumbnailUrl" varchar(1024),
	"createdAt" timestamp with time zone NOT NULL,
	"updatedAt" timestamp with time zone
);
--> statement-breakpoint
CREATE TABLE "zenflix_watch_history" (
	"id" uuid PRIMARY KEY NOT NULL,
	"watchDuration" integer DEFAULT 0 NOT NULL,
	"completed" boolean DEFAULT false NOT NULL,
	"videoId" uuid NOT NULL,
	"profileId" uuid NOT NULL,
	"lastWatchedAt" timestamp with time zone NOT NULL,
	CONSTRAINT "watch_history_video_profile_unique" UNIQUE("videoId","profileId")
);
--> statement-breakpoint
ALTER TABLE "zenflix_account" ADD CONSTRAINT "zenflix_account_userId_zenflix_user_id_fk" FOREIGN KEY ("userId") REFERENCES "public"."zenflix_user"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "zenflix_profile" ADD CONSTRAINT "zenflix_profile_userId_zenflix_user_id_fk" FOREIGN KEY ("userId") REFERENCES "public"."zenflix_user"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "zenflix_review" ADD CONSTRAINT "zenflix_review_videoId_zenflix_video_id_fk" FOREIGN KEY ("videoId") REFERENCES "public"."zenflix_video"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "zenflix_review" ADD CONSTRAINT "zenflix_review_userId_zenflix_user_id_fk" FOREIGN KEY ("userId") REFERENCES "public"."zenflix_user"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "zenflix_session" ADD CONSTRAINT "zenflix_session_userId_zenflix_user_id_fk" FOREIGN KEY ("userId") REFERENCES "public"."zenflix_user"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "zenflix_video_category" ADD CONSTRAINT "zenflix_video_category_videoId_zenflix_video_id_fk" FOREIGN KEY ("videoId") REFERENCES "public"."zenflix_video"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "zenflix_video_category" ADD CONSTRAINT "zenflix_video_category_categoryId_zenflix_category_id_fk" FOREIGN KEY ("categoryId") REFERENCES "public"."zenflix_category"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "zenflix_watch_history" ADD CONSTRAINT "zenflix_watch_history_videoId_zenflix_video_id_fk" FOREIGN KEY ("videoId") REFERENCES "public"."zenflix_video"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "zenflix_watch_history" ADD CONSTRAINT "zenflix_watch_history_profileId_zenflix_profile_id_fk" FOREIGN KEY ("profileId") REFERENCES "public"."zenflix_profile"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
CREATE INDEX "account_user_id_idx" ON "zenflix_account" USING btree ("userId");--> statement-breakpoint
CREATE INDEX "review_video_idx" ON "zenflix_review" USING btree ("videoId");--> statement-breakpoint
CREATE INDEX "t_user_id_idx" ON "zenflix_session" USING btree ("userId");--> statement-breakpoint
CREATE INDEX "video_category_category_idx" ON "zenflix_video_category" USING btree ("categoryId");--> statement-breakpoint
CREATE INDEX "video_name_idx" ON "zenflix_video" USING btree ("name");--> statement-breakpoint
CREATE INDEX "watch_history_profile_idx" ON "zenflix_watch_history" USING btree ("profileId");